import React, { useCallback, useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import PAInput from '@/components/PAInput'
import PAButton from '@/components/PAButton'
import PAToggle from '@/components/PAToggle'
import Recipe from '@/components/Recipe'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [ inputValue, setInputValue ] = useState('');
    const [ toggleValue, setToggleValue ] = useState('');

    const onChangeValue = useCallback(({ value }) => {
        setInputValue(value);
    }, [ setInputValue ]);

    const onToggle = useCallback(({ value }) => {
        setToggleValue(value);
    }, [ setToggleValue ]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Recipe />
            </main>
        </>
    )
}
